kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certmerge-operator
subjects:
- kind: ServiceAccount
  name: certmerge-operator
  namespace: cert-merge
roleRef:
  kind: ClusterRole
  name: certmerge-operator
  apiGroup: rbac.authorization.k8s.io
